### ISSUE TITLE
Handle missing databases with voice message rather than error

### ISSUE THREAD

**Issue by marksev1** [Cadair/mycroft-kodi#1]
So what do I need to set up in Kodi for this to work?

Also do I need to put something in mycroft.ini or how does it find the correct address and port for Kodi?

Also does it also work with addons for searching movies inside of there?

**Comment by Cadair** [comment]
In Kodi this just needs the HTTP remote control setting enabled (I can't remember exactly what this is called).

Currently, you have to change the IP of your kodi instance in the source code itself, I never got as far as using the ini file.

I believe it works with anything that hooks into the core kodi database, for instance I was searching for things added by the Emby extension. It won't find things in non-database extensions to my knowledge.

**Comment by marksev1** [comment]
Thanks, yeah found that after googling in the forum thread. Gonna try it out :).

**Comment by marksev1** [comment]
Actually if I could maybe reuse this issue:

2016-10-30 09:29:59,941 - Skills - DEBUG - {"message_type": "intent_failure", "context": null, "metadata": {"utterance": "search for movie the matrix"}}

Dunno why it constantly fails in detecting intent.

Also this error:

2016-10-31 12:40:38,859 - mycroft.configuration - DEBUG - Configuration '/home/msev/.mycroft/mycroft.ini' not found
2016-10-31 12:40:38,861 - mycroft.messagebus.client.ws - INFO - Connected
2016-10-31 12:40:38,916 - mycroft.skills.core - ERROR - Failed to load skill: 
Traceback (most recent call last):
  File "/home/msev/mycroft-core/mycroft/skills/core.py", line 105, in load_skill
    skill = skill_module.create_skill()
  File "/home/msev/mycroft-core/mycroft/skills/mycroft-kodi-master/**init**.py", line 109, in create_skill
    return KodiSkill()
  File "/home/msev/mycroft-core/mycroft/skills/mycroft-kodi-master/**init**.py", line 25, in **init**
    self.kodi = Kodi('192.168.88.192:8080')
  File "/home/msev/.virtualenvs/mycroft/local/lib/python2.7/site-packages/kodipydent/KodiClient.py", line 53, in Kodi
    hive = Hive(get_rpc.API.get())
  File "/home/msev/.virtualenvs/mycroft/local/lib/python2.7/site-packages/beekeeper/api.py", line 195, in execute
    _timeout=self.timeout
  File "/home/msev/.virtualenvs/mycroft/local/lib/python2.7/site-packages/beekeeper/comms.py", line 97, in send
    resp = Response(self.action.format(), request(timeout=timeout, *_self.output), traversal)
  File "/home/msev/.virtualenvs/mycroft/local/lib/python2.7/site-packages/beekeeper/comms.py", line 64, in request
    return REQUEST_OPENER.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

Actually if i change the url to be without the port number I dont get that error anymore...So yeah just the intent problem i guess...

**Comment by marksev1** [comment]
If I run from the skill container it registers intent but doesn't work anyway:)

2016-10-31 12:48:51,028 - SkillContainer - DEBUG - {"message_type": "recognizer_loop:utterance", "context": null, "metadata": {"utterances": ["search for movie The Matrix"]}}
2016-10-31 12:48:51,032 - SkillContainer - DEBUG - {"message_type": "SearchFilmsIntent", "context": {"target": null}, "metadata": {"confidence": 0.7777777777777777, "target": null, "SearchFilmKeywords": "search for movie", "intent_type": "SearchFilmsIntent", "utterance": "search for movie The Matrix", "Film": "the matrix"}}
2016-10-31 12:48:51,034 - mycroft.skills.core - ERROR - An error occurred while processing a request in KodiSkill
Traceback (most recent call last):
  File "/home/msev/mycroft-core/mycroft/skills/core.py", line 206, in receive_handler
    handler(message)
  File "/home/msev/mycroft-core/mycroft/skills/mycroft-kodi-master/**init**.py", line 55, in handle_film_search_intent
    results = kodi.find_films_matching(self.kodi, message.metadata['Film'])
  File "/home/msev/mycroft-core/mycroft/skills/mycroft-kodi-master/kodi.py", line 27, in find_films_matching
    movies = kodi.VideoLibrary.GetMovies()['result']['movies']
KeyError: 'movies'
2016-10-31 12:48:51,035 - SkillContainer - DEBUG - {"message_type": "speak", "context": null, "metadata": {"utterance": "An error occurred while processing a request in KodiSkill"}}

**Comment by Cadair** [comment]
What version of kodi are you using? I might have a chance to have a look at this in a couple of weeks time, but I can't make any promises.

**Comment by marksev1** [comment]
Kodi 17, the beta version...But you know what, this doesn't search the addons right, since kodi json api doesn't expose that...since I don't have any local content besides music yet it isn't that much of use...But is a cool display of Mycrofts powers. Would be nice if it could be somehow hacked to search the addons too :D

**Comment by Cadair** [comment]
if you don't have a movie database that's probably why it's erroring as above. I will keep this open to remind me that these keys might not exist.

**Comment by marksev1** [comment]
Is it possible to hack functionality similiar to Yatse remote app which has the option to search through addons albeit via "text"?

**Comment by Cadair** [comment]
If Yatse can do it maybe it is. Can you open a new issue for it?
