### ISSUE TITLE
If Kodi is not running skill doesn't get loaded

### ISSUE THREAD

**Issue by marksev1** [Cadair/mycroft-kodi#4]
As the description says...Thats not a good behaviour imho...

**Comment by marksev1** [comment]
Also off topic but this happens: 

(instead of play movie i choose "roll movie")

2016-12-09 19:35:18,834 - Skills - DEBUG - {"message_type": "recognizer_loop:utterance", "metadata": {"utterances": ["roll movie Westworld"]}}
2016-12-09 19:35:18,836 - Skills - DEBUG - {"message_type": "PlayFilmsIntent", "context": {"target": null}, "metadata": {"confidence": 0.725, "PlayFilmKeywords": "roll movie", "target": null, "intent_type": "PlayFilmsIntent", "utterance": "roll movie Westworld", "Film": "westworld"}}
2016-12-09 19:35:18,836 - mycroft.skills.core - ERROR - An error occurred while processing a request in KodiSkill
Traceback (most recent call last):
  File "/home/msev/mycroft-core/mycroft/skills/core.py", line 206, in receive_handler
    handler(message)
  File "/home/msev/mycroft-core/mycroft/skills/kodiskill/__init__.py", line 47, in handle_play_film_intent
    kodi.play_film_by_search(self.kodi, message.metadata['Film'])
	  
movie", "intent_type": "SearchFilmsIntent", "utterance": "search for movie Westworld", "Film": "westworld"}}
2016-12-09 19:34:57,984 - mycroft.skills.core - ERROR - An error occurred while processing a request in KodiSkill
Traceback (most recent call last):
  File "/home/msev/mycroft-core/mycroft/skills/core.py", line 206, in receive_handler
    handler(message)
  File "/home/msev/mycroft-core/mycroft/skills/kodiskill/__init__.py", line 55, in handle_film_search_intent
    results = kodi.find_films_matching(self.kodi, message.metadata['Film'])
  File "/home/msev/mycroft-core/mycroft/skills/kodiskill/kodi.py", line 27, in find_films_matching
    movies = kodi.VideoLibrary.GetMovies()['result']['movies']
KeyError: 'movies'
